name: kapiot
description: A Proof of Concept of a Carpooled Ridesharing System for the USC Community

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  google_sign_in: ^5.0.7
  hooks_riverpod: ^1.0.0-dev.6
  google_maps_flutter: ^2.0.6
  geolocator: ^7.4.0
  flutter_hooks: ^0.18.0
  sliding_up_panel: ^2.0.0+1
  freezed_annotation: ^0.14.3

dev_dependencies:
  build_runner: ^2.1.1
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  mockito: ^5.0.14

flutter:
  uses-material-design: true
