name: kapiot
description: A Proof of Concept of a Carpooled Ridesharing System for the USC Community

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Core (State management, error handling, etc.)
  hooks_riverpod: ^1.0.0-dev.6
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.3
  dartz: ^0.10.0
  # Firebase-related
  cloud_firestore: ^2.5.0
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_auth_mocks: ^0.8.0
  # Google-related
  google_sign_in: ^5.0.7
  google_sign_in_mocks: ^0.2.1
  google_place: ^0.4.3
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  maps_toolkit: ^2.0.0
  # Location
  geolocator: ^7.4.0
  geocoding: ^2.0.0
  # Design
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^9.1.0
  marquee: ^2.2.0
  jiffy: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  mockito: ^5.0.14
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/images/
    - lib/ui/assets/icons/
  fonts:
    - family: Sanz
      fonts:
        - asset: lib/ui/assets/fonts/RNSSanz-Bold.otf
    - family: Vegur
      fonts:
        - asset: lib/ui/assets/fonts/Vegur-Regular.otf
        - asset: lib/ui/assets/fonts/Vegur-Light.otf
          weight: 300
        - asset: lib/ui/assets/fonts/Vegur-Bold.otf
          weight: 700
