// Mocks generated by Mockito 5.0.16 from annotations
// in kapiot/test/data/core/core_algo_point_system_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:kapiot/data/services/google_maps_api_services.dart' as _i3;
import 'package:kapiot/model/dist_matrix_element/dist_matrix_element.dart'
    as _i2;
import 'package:kapiot/model/kapiot_location/kapiot_location.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDistMatrixElement_0 extends _i1.Fake
    implements _i2.DistMatrixElement {}

/// A class which mocks [DistanceMatrixService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDistanceMatrixService extends _i1.Mock
    implements _i3.DistanceMatrixService {
  MockDistanceMatrixService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DistMatrixElement> getDistMatrixElement(
          {_i5.KapiotLocation? pointA, _i5.KapiotLocation? pointB}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getDistMatrixElement, [], {#pointA: pointA, #pointB: pointB}),
          returnValue: Future<_i2.DistMatrixElement>.value(
              _FakeDistMatrixElement_0())) as _i4
          .Future<_i2.DistMatrixElement>);
  @override
  String toString() => super.toString();
}
